#!/bin/bash

CACHE_DIR="$HOME/.cache/wal"

FIREFOX_PROFILES_DIR="$HOME/.config/mozilla/firefox"
CONFIG_DIR="$HOME/.config"

# -------------------------------------------------------------

WALLPAPER=$(cat "$CACHE_DIR/wal")

if [[ -z "$WALLPAPER" ]]; then
    echo "No cached wallpaper found."
    exit 1
fi

# -------------------------------------------------------------
# generate pywal colors
# -------------------------------------------------------------

wal -i "$WALLPAPER" -n 2>&1 | grep -v "^\[\|WARNING\|warning" || true

source "$CACHE_DIR/colors.sh"

# map to short variable names used in templates
C0=$color0;   C1=$color1;   C2=$color2;   C3=$color3
C4=$color4;   C5=$color5;   C6=$color6;   C7=$color7
C8=$color8;   C9=$color9;   C10=$color10; C11=$color11
C12=$color12; C13=$color13; C14=$color14; C15=$color15
FG=$foreground; BG=$background

# -------------------------------------------------------------

echo "Generating configurations for wallpaper: $WALLPAPER"

# -------------------------------------------------------------
# regenerate hyprpaper wallpaper
# -------------------------------------------------------------

echo "[+] Generating hyprpaper config..."

HYPERPAPER_CONF=$(cat << HYPER
preload = $WALLPAPER
wallpaper = ,$WALLPAPER
HYPER
)

echo "$HYPERPAPER_CONF" > "$CONFIG_DIR/hypr/hyprpaper.conf"

# apply wallpaper immediately
awww img "$WALLPAPER" --transition-type fade --transition-duration 1 2>/dev/null || \
    hyprctl hyprpaper wallpaper ",$WALLPAPER"

# -------------------------------------------------------------
# regenerate fuzzel config
# -------------------------------------------------------------

echo "[+] Generating fuzzel config..."

FUZZEL_INI=$(cat << FUZZEL
[main]
font = Iosevka Nerd Font Mono:size=12
prompt = run:

[border]
width = 1
radius = 6

[colors]
background = ${C0#\#}dd
text = ${FG#\#}ee
selection = ${C4#\#}44
selection-text = ${FG#\#}ee
match = ${C2#\#}ee
placeholder = ${C8#\#}88
input = ${FG#\#}ee
prompt = ${FG#\#}ee
border = ${C4#\#}cc
FUZZEL
)

echo "$FUZZEL_INI" > "$CONFIG_DIR/fuzzel/fuzzel.ini"

# -------------------------------------------------------------
# regenerate hypr pywal.lua
# -------------------------------------------------------------

echo "[+] Generating hypr pywal.lua..."

hex_to_rgba() {
    python3 -c "h='$1'; print(f'rgba({int(h[1:3],16)},{int(h[3:5],16)},{int(h[5:7],16)},{$2})')"
}

C0_RGBA=$(hex_to_rgba "$C0" "0.8")
C0_RGBA_HIGH=$(hex_to_rgba "$C0" "0.92")
C4_RGBA=$(hex_to_rgba "$C4" "0.9")
C8_RGBA=$(hex_to_rgba "$C8" "0.7")
BG_RGBA=$(hex_to_rgba "$BG" "0.8")
FG_RGBA=$(hex_to_rgba "$FG" "1.0")

PYWAL_LUA=$(cat << LUA
-- Autogenerated pywal colors
-- Source: wal

return {
    activeBorder        = "$C4_RGBA",
    inactiveBorder      = "$C0_RGBA",

    cursorColor         = "$C4",
    borderColor         = "$C4",
    activeBorderColor   = "$C4",
    inactiveBorderColor = "$C0",
    urgentBorderColor   = "$C1",

    background = "$C0",
    foreground = "$FG",

    groupBorderActive   = "$C4_RGBA",
    groupBorderInactive = "$C0_RGBA",
    groupbarText        = "$FG_RGBA",
    groupbarTextInactive = "$C8_RGBA",
    groupbarBgActive    = "$C0_RGBA_HIGH",
    groupbarBgInactive  = "$BG_RGBA",

    color0  = "$C0",
    color1  = "$C1",
    color2  = "$C2",
    color3  = "$C3",
    color4  = "$C4",
    color5  = "$C5",
    color6  = "$C6",
    color7  = "$C7",
    color8  = "$C8",
    color9  = "$C9",
    color10 = "$C10",
    color11 = "$C11",
    color12 = "$C12",
    color13 = "$C13",
    color14 = "$C14",
    color15 = "$C15",
}
LUA
)

rm -f "$CONFIG_DIR/hypr/pywal.lua"
echo "$PYWAL_LUA" > "$CACHE_DIR/pywal.lua"
ln -s "$CACHE_DIR/pywal.lua" "$CONFIG_DIR/hypr/pywal.lua"

# -------------------------------------------------------------
# regenerate hyprlock.conf
# -------------------------------------------------------------

echo "[+] Generating hyprlock config..."

HYPRLOCK=$(cat << HYPRLOCK
background {
    monitor = ""
    path = screenshot
    blur_passes = 0
    blur_size = 1
    noise = 0.0117
    contrast = 1.0
    brightness = 0.8
    vibrancy = 0.21
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(127, 127, 127, 0.4)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = $FG_RGBA
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] echo "\$(date +'%A, %B %d')"
    color = $FG_RGBA
    font_size = 20
    font_family = Inter Bold
    position = 0, -35
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] echo "\$(date +'%H:%M')"
    color = $FG_RGBA
    font_size = 96
    font_family = Inter Bold
    position = 0, 60
    halign = center
    valign = center
}
HYPRLOCK
)

echo "$HYPRLOCK" > "$CONFIG_DIR/hypr/hyprlock.conf"


# -------------------------------------------------------------
# regenerate ghostty config
# -------------------------------------------------------------

echo "[+] Generating ghostty config..."

GHOSTTY=$(cat << GHOSTTY
background = $BG
foreground = $FG
cursor-color = $FG

palette = 0=$C0
palette = 1=$C1
palette = 2=$C2
palette = 3=$C3
palette = 4=$C4
palette = 5=$C5
palette = 6=$C6
palette = 7=$C7
palette = 8=$C8
palette = 9=$C9
palette = 10=$C10
palette = 11=$C11
palette = 12=$C12
palette = 13=$C13
palette = 14=$C14
palette = 15=$C15

window-decoration = none
font-family = Iosevka Nerd Font
font-size = 12
keybind = ctrl+n=new_tab
keybind = ctrl+w=close_tab
GHOSTTY
)

echo "$GHOSTTY" > "$CONFIG_DIR/ghostty/config"

# Reload Ghostty config live via D-Bus (no restart needed)
gdbus call --session --dest com.mitchellh.ghostty \
    --object-path /com/mitchellh/ghostty \
    --method org.freedesktop.Application.ActivateAction \
    "reload-config" "[]" "{}" 2>/dev/null || true

# Apply colors to running terminals via escape sequences
WAL_SEQUENCES="$CACHE_DIR/sequences"
for pts in /dev/pts/[0-9]*; do
    [ -w "$pts" ] && cat "$WAL_SEQUENCES" > "$pts" 2>/dev/null || true
done

# reload configs
pkill -SIGUSR2 waybar 2>/dev/null || true
hyprctl reload 2>/dev/null || true

echo "done"
